require 'rubygems'
require 'bundler/setup'
require 'active_record'
require 'nokogiri'
require 'optparse'
require $PATH + 'config/application'
require $PATH + 'app/controllers/sync_controller'
require $PATH + 'app/models/product'
require $PATH + 'app/models/producto'
require $PATH + 'app/models/inventario'
